backend:
  name: github
  repo: suresh-kumara-gist/biothermica-site-hs-18-feb-2026
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org/
  auth_endpoint: /auth/github/repo/6995f009f3f9aacf96d58e5f

media_folder: "sites/biothermica.com/files"
public_folder: "sites/biothermica.com/files"

collections:

  - name: "en_pages"
    label: "English Pages"
    folder: "docs/en"
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    filter:
      field: "lang"
      value: "en"

