backend:
  name: github
  repo: suresh-kumara-gist/biothermica-site-hs-18-feb-2026
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org/
  auth_endpoint: /auth/github/repo/6995f009f3f9aacf96d58e5f

media_folder: "docs/sites/biothermica.com/files"
public_folder: "docs/sites/biothermica.com/files"

collections:
  - name: "en_air_pollution_control_projects"
    label: "EN Air Pollution Control Projects"
    folder: "docs/en/air-pollution-control/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Project ID", name: "project_id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "default2" }
    filter:
      field: "lang"
      value: "en"

  - name: "en_assainissement_projects"
    label: "EN Assainissement Projects"
    folder: "docs/en/assainissement/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Project ID", name: "project_id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "content" }
    filter:
      field: "lang"
      value: "en"

  - name: "en_carbon_and_energy"
    label: "EN Carbon And Energy"
    folder: "docs/en/carbon-and-energy"
    create: true
    extension: "html"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "content" }
    filter:
      field: "lang"
      value: "en"


  # - name: "en_contactez"
  #   label: "Contactez (EN)"
  #   folder: "docs/en/content/contactez"
  #   # nested:
  #   #   depth: 3
  #   extension: "html"
  #   create: true
  #   delete: true
  #   format: "frontmatter"
  #   fields:
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
  #     - { label: "Language", name: "lang", widget: "hidden", default: "en" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
  #     - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
  #     - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
  #     - { label: "Permalink", name: "permalink", widget: "string" }
  #     - { label: "Path EN", name: "path_en", widget: "string", required: false }
  #     - { label: "Path FR", name: "path_fr", widget: "string", required: false }

  #     - label: "Page Content (HTML)"
  #       name: "body"
  #       widget: "code"
  #       default_language: "html"
  #       output_code_only: true

  #   filter:
  #     field: "lang"
  #     value: "en"

  - name: "en_content"
    label: "Contents (EN)"
    folder: "docs/en/content"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "content" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "en"


  - name: "en_documents"
    label: "Documents (EN)"
    folder: "docs/en/documents"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "document" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "en"

  - name: "en_tags"
    label: "Tags (EN)"
    folder: "docs/en/tags"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "tag" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }
      - { lalabel: "Term ID", name: "termId", widget: "number", value_type: "int" }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "en"

# /Users/apple/business/snamy-groups/snamy-technologies/projects/services/dcycle/biothermica-site-hs-18-feb-2026/docs/fr/https_/www.biothermica.com/fr/content/carbone-et-énergie/bioenergie-togo.html
# /Users/apple/business/snamy-groups/snamy-technologies/projects/services/dcycle/biothermica-site-hs-18-feb-2026/docs/en/https_/www.biothermica.com/content/carbon-and-energy/bioenergy-togo.html

  - name: "en_pages"
    label: "English Pages"
    folder: "docs/en"
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "en"


#French collections
  - name: "fr_air_pollution_control_projects"
    label: "FR Air Pollution Control Projects"
    folder: "docs/fr/air-pollution-control/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Project ID", name: "project_id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "default-fr" }      
    filter:
      field: "lang"
      value: "fr"

  - name: "fr_assainissement_projects"
    label: "FR Assainissement Projects"
    folder: "docs/fr/assainissement/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Project ID", name: "project_id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "content-fr" }
    filter:
      field: "lang"
      value: "fr"

  - name: "fr_contactez"
    label: "Contactez (FR)"
    folder: "docs/fr/content/contactez"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "content-fr" }
      - { label: "Language", name: "lang", widget: "hidden", default: "fr" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "fr"

  - name: "fr_content"
    label: "Contents (FR)"
    folder: "docs/fr/content"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "content-fr" }
      - { label: "Language", name: "lang", widget: "hidden", default: "fr" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "fr"


  - name: "fr_documents"
    label: "Documents (FR)"
    folder: "docs/fr/documents"
    # nested:
    #   depth: 3
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "document-fr" }
      - { label: "Language", name: "lang", widget: "hidden", default: "fr" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "fr"

  - name: "fr_tags"
    label: "Tags (FR)"
    folder: "docs/fr/tags"
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "tag-fr" }
      - { label: "Language", name: "lang", widget: "hidden", default: "fr" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }
      - { lalabel: "Term ID", name: "termId", widget: "number", value_type: "int" }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "fr"

# /Users/apple/business/snamy-groups/snamy-technologies/projects/services/dcycle/biothermica-site-hs-18-feb-2026/docs/fr/https_/www.biothermica.com/fr/content/carbone-et-énergie/bioenergie-togo.html
# /Users/apple/business/snamy-groups/snamy-technologies/projects/services/dcycle/biothermica-site-hs-18-feb-2026/docs/en/https_/www.biothermica.com/content/carbon-and-energy/bioenergy-togo.html

  - name: "fr_pages"
    label: "French Pages"
    folder: "docs/fr"
    extension: "html"
    create: true
    delete: true
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
      - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
      - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Path EN", name: "path_en", widget: "string", required: false }
      - { label: "Path FR", name: "path_fr", widget: "string", required: false }

      - label: "Page Content (HTML)"
        name: "body"
        widget: "code"
        default_language: "html"
        output_code_only: true

    filter:
      field: "lang"
      value: "fr"













  # - name: "en_homepage"
  #   label: "EN Homepage"
  #   files:
  #     - file: "docs/en/index.html"
  #       label: "Homepage"
  #       name: "en_home"
  #       fields:
  #         - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
  #         - { label: "Language", name: "lang", widget: "hidden", default: "en" }
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
  #         - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
  #         - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
  #         - { label: "Permalink", name: "permalink", widget: "string" }
  #         - { label: "Path EN", name: "path_en", widget: "string", required: false }
  #         - { label: "Path FR", name: "path_fr", widget: "string", required: false }
  
  #         - label: "Page Content (HTML)"
  #           name: "body"
  #           widget: "code"
  #           default_language: "html"
  #           output_code_only: true

  # - name: "en_pages"
  #   label: "English Pages"
  #   folder: "docs/en"
  #   extension: "html"
  #   create: true
  #   format: "frontmatter"
  #   fields:
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
  #     - { label: "Language", name: "lang", widget: "hidden", default: "en" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
  #     - { label: "Meta Description", name: "meta_description", widget: "text", required: false }
  #     - { label: "RSS Feed Title", name: "rss_feed_title", widget: "string", required: false }
  #     - { label: "Permalink", name: "permalink", widget: "string" }
  #     - { label: "Path EN", name: "path_en", widget: "string", required: false }
  #     - { label: "Path FR", name: "path_fr", widget: "string", required: false }

  #     - label: "Page Content (HTML)"
  #       name: "body"
  #       widget: "code"
  #       default_language: "html"
  #       output_code_only: true

  #   filter:
  #     field: "lang"
  #     value: "en"

