backend:
  name: github
  repo: biothermica/biothermica-site
  branch: main
  base_url: https://app.staticauth.com
  auth_endpoint: /auth/github/repo/6995f009f3f9aacf96d58e5f

media_folder: "sites/biothermica.com/files"
public_folder: "sites/biothermica.com/files"

collections:

  - name: "en_pages"
    label: "English Pages"
    folder: "docs/en"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "en_assainissement_projects"
    label: "EN Assainissement Projects"
    folder: "docs/en/assainissement/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      # - { label: "Project ID", name: "project_id", widget: "string" }
      # - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "en_air_pollution_projects"
    label: "EN Air Pollution Control Projects"
    folder: "docs/en/air-pollution-control/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      # - { label: "Category ID", name: "category_id", widget: "string" }
      # - { label: "Project ID", name: "project_id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "documents_en"
    label: "Documents EN"
    folder: "docs/en/documents"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Document Title", name: "title", widget: "string" }
      - { label: "File Upload", name: "file", widget: "file" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "en_tags"
    label: "EN Tags"
    folder: "docs/en/tags"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Tag Name", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }




  - name: "fr_air_projects"
    label: "FR Air Pollution Projects"
    folder: "docs/fr/air-pollution-control/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      - { label: "ID Projet", name: "project_id", widget: "string" }
      - { label: "ID Cat√©gorie", name: "category_id", widget: "string" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }


  - name: "fr_pages"
    label: "French Pages"
    folder: "docs/fr"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "fr_assainissement_projects"
    label: "FR Assainissement Projects"
    folder: "docs/fr/assainissement/projects"
    create: true
    nested:
      depth: 3
    extension: "html"
    format: "frontmatter"
    slug: "{{fields.project_id}}"
    fields:
      # - { label: "Project ID", name: "project_id", widget: "string" }
      # - { label: "Category ID", name: "category_id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "documents_fr"
    label: "Documents FR"
    folder: "docs/en/documents"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Document Title", name: "title", widget: "string" }
      # - { label: "File Upload", name: "file", widget: "file" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "fr_tags"
    label: "FR Tags"
    folder: "docs/fr/tags"
    create: true
    extension: "html"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Tag Name", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
